//= Day 1: variable and data types

//- Activity 1
//? Task 1 Declare var assign number

var Seatno = 3295;

console.log(Seatno);
console.log(typeof Seatno);

//? Task 2 Declare let assign string

let userName = "Ashish Ramchandra"

console.log(userName);
console.log(typeof userName);


//- Activity 2
//? Task 3 Declare const assign boolean

const correctEmail = true;

console.log(correctEmail);
console.log(typeof correctEmail);