//= DAY 2 OPERATORS
//-ACTIVITY 1


//? TASK 1 ADD TWO NUM

MATHS = 50;
ENGLISH = 70;

results = MATHS + ENGLISH

console.log(results);

//? TASK 2 subtract TWO NUM

MarksOne = 344
subtract = 32

MarksDeductions = MarksOne - subtract
console.log(MarksDeductions);



//? TASK 3 multiply TWO NUM

firstMulti = 33
secMulti = 4

sumMultiply = firstMulti * secMulti

console.log(sumMultiply);


//? TASK 4 divide TWO NUM
divOne = 254
divTwo = 34

division = divOne / divTwo
console.log(division);





//? TASK 5 remainder TWO NUM

rem = 304
remain = 3

remainder = rem % remain
console.log(remainder);

//-ACTIVITY 2
//? TASK 6 += ADD TO VARIABLE

let vOne = 12
vOne += 54
console.log(vOne);


//? TASK 7 -= subtract TO VARIABLE
let minus = 2332;

minus -= 2;

console.log(minus);



//-ACTIVITY 3
//? TASK 8  TWO NUM > and <

let numOne = 40
let numTwo = 60

console.log(numOne > numTwo);
console.log(numOne < numTwo);

//? TASK 9  TWO NUM >= and <=

let greater = 50
let lesser = 404

console.log(greater >= lesser);
console.log(greater <= lesser);

//? TASK 10  TWO NUM == and ===

let equal = 3032
let equalThree = "3032"

console.log(equal == equalThree);
console.log(equal === equalThree);


//-ACTIVITY 4
//? TASK 11 ADD TWO NUM && OPERATOR

let andOp = 31
let andOPP = 30

let andOp1 = andOp > andOPP  // check where the condition true or not or until and unless both the codition is true it won't give true
let andOp2 = andOp === 31

console.log('Check condition', andOp1 && andOp2)
console.log('Check condition', andOp === 31 && andOp > andOPP) // same as with variable



//? TASK 11 ADD TWO NUM || OPERATOR

let orOP = 203
let oroperator = 334

console.log("lets check the codition: ", orOP < oroperator || orOP === 403); // if any condition where true is present then the result will true or false


//? TASK 11 ADD TWO NUM ! OPERATOR

let NotOp = 303
let notOPP= 40

console.log("lets check the codition: ", !NotOp < notOPP); // if the condition is true it will print false it's mean opposite of true



//-ACTIVITY 4
//? TASK 12  ternary operator 

let driverAge = 10

let checkEligible = driverAge >18 ? "adult" : "minor" // if the condition is true then it will print adult otherwise it will print minor

console.log(checkEligible);