//= Day 1: variable and data types

//- Activity 1
//? Task 1 Declare var assign number

var Seatno = 3295;

console.log(Seatno);
console.log(typeof Seatno);

//? Task 2 Declare let assign string

let userName = "Ashish Ramchandra"

console.log(userName);
console.log(typeof userName);


//- Activity 2
//? Task 3 Declare const assign boolean

const correctEmail = true;

console.log(correctEmail);
console.log(typeof correctEmail);


//- Activity 3
//? Task 4 Variable of Different data types assign number, string, boolean, object, and array

const phoneNo = 100000090000;

console.log(phoneNo);
console.log(typeof phoneNo);

const phoneUser = "someone harshil"

console.log(phoneUser);
console.log(typeof phoneUser);


let isloggedin = false

console.log(isloggedin);
console.log(typeof isloggedin);


let myObj = {
    usernameOne: "Jogi",
    userphone: 4000030000,
    isUserverified: true,
    userEmail: "usersomeone@gmail.com"
}

console.log(myObj);
console.log(typeof myObj);


const userCart = ["Shoes","Shirts", "Cargo", "Crocs"]
console.log(userCart);
console.log(typeof userCart);

//- Activity 4
//? Task 5 Declare a variable and reassign a value

let userEmails = "firstemail@gmail.com"
console.log(userEmails);
userEmails = "second@gmail.com"
console.log(userEmails);

//- Activity 5
//? Task 6 Declare a variable and reassign const a value
const useractivity = "enterpress"
console.log(useractivity);
useractivity = "enterpress"
console.log(useractivity);